mixed-port: 7890
# 允许局域网的连接（可用来共享代理）
allow-lan: true
# 仅在将allow-lan设置为true时适用
# #"*": 绑定所有IP地址
# #192.168.122.11: 绑定单个IPv4地址
# #"[aaaa::a8aa:ff:fe09:57d8]": 绑定单个IPv6地址
bind-address: '*'
# 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script (脚本)
mode: rule
# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / error / warning / info / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info
# Clash 的 RESTful API
external-controller: '127.0.0.1:9090'

# 实验性功能 hosts, 支持通配符 (例如 *.clash.dev 甚至 *.foo.*.example.com)
# 静态的域名 比 通配域名 具有更高的优先级 (foo.example.com 优先于 *.example.com)
# 注意: hosts 在 fake-ip 模式下不生效
#hosts:
#   '*.clash.dev': 127.0.0.1
#   'alpha.clash.dev': '::1'

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  default-nameserver:   # 默认 dns, 用于解析 DNS 服务器 的域名
    - 223.5.5.5         # 阿里
    - 119.29.29.29      # DNSpod DNS
  enhanced-mode: fake-ip # 模式：redir-host或fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: # fake ip 白名单列表，如果你不知道这个参数的作用，请勿修改
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '*.msftconnecttest.com'
    - '+.msftncsi.com'

  # nameserver-policy:
  #   rule-set:company: 172.26.1.250

  nameserver:
    # - 223.5.5.5         # 阿里
    # - 119.29.29.29      # DNSpod DNS
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query

  # proxy-server-nameserver:  # 当proxy里的server为域名时，使用该列表里的dns服务器解析。无此字段的时候，使用nameserver列表里的dns解析；
  #   - tls://1.0.0.1:853

  fallback:
    - https://doh.dns.sb/dns-query
    - tls://8.8.8.8:853         # Google DNS over TLS 50ms
    - tls://8.8.4.4:853         # cloudflare DNS over TLS 50ms
    - https://1.1.1.1/dns-query # cloudflare DNS over HTTPS
    - https://dns.google/dns-query # Google DNS over HTTPS
  fallback-filter:
     geoip: true
     geoip-code: CN
     geosite: 
       - gfw     #geosite中的gfw分类使用fallback内的dns解析
     ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
       - 240.0.0.0/4
       - 0.0.0.0/32

# 1. clash DNS 请求逻辑：
#   (1) 当访问一个域名时， nameserver 与 fallback 列表内的所有服务器并发请求，得到域名对应的 IP 地址。
#   (2) clash 将选取 nameserver 列表内，解析最快的结果。
#   (3) 若解析结果中，IP 地址属于 国外，那么 clash 将选择 fallback 列表内，解析最快的结果。
#
sniffer:
  enable: true
  sniffing:
    - tls
    - http
  skip-domain:
    - 'Mijia Cloud'
    - 'dlg.io.mi.com'
    - '+.apple.com'
    
  force-domain:
    # - '+'   # 强制全局嗅探
    - 'google.com'
    - '*.netflix.com.com'
    
  # port-whitelist:   # 端口白名单，只对名单内的端口进行嗅探还原域名（不写为全端口）。
  #   - 443
  #   - 8000-9000
